#baseurl: "/2017"

title: "BuildingBloCS + CTE-STEM"
tagline: "High School Computing Conference"
date: "Wed 2 June - Fri 4 June"
location: "Online / In Person"
instagram: "buildingblocs21"
github: "buildingblocs"

exclude:
  - README.md
  - assets/sass
  - package.json
  - package-lock.json
  - node_modules/
  - Gruntfile.js
  - .jekyll-cache/